#!/usr/bin/env python3
import subprocess
import os
import sys
import shutil

def get_parent_dir():
    return 'new_c-blosc2'

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("./debug \"0 1 0 1 0 1\"");
        sys.exit()

    project = get_parent_dir()
    subprocess.run(['rm', '-f', '*.json', 'fuzz_exec', 'fuzz_write', 'crash-*', 'leak-*'])
    subprocess.run(['docker', 'run', '-t', '-d', '--name', f'{project}', '-v', '.:/tmp', f'sb_{project}', '/bin/bash'])

    subprocess.run(['docker', 'exec', '-w', '/new_fuzzing_driver/c-blosc2/build', f'{project}', 'sh', '-c', f'./debug.sh \"{sys.argv[1]}\" | tee /tmp/test.log'])

    subprocess.run(['docker', 'kill', f'{project}'])
    subprocess.run(['docker', 'rm', f'{project}'])

    print("result saved: test.log")
